export const SET_ALL_RESERVATIONS = 'SET_ALL_RESERVATIONS'
export const CLEAR_ALL_RESERVATIONS = 'CLEAR_ALL_RESERVATIONS'

export const GET_ALL_RESERVATIONS_ADMIN = 'GET_ALL_RESERVATIONS_ADMIN'

export const SET_RESERVATION_TO_EDIT = 'SET_RESERVATION_TO_EDIT'

export const CLEAR_ALL_RESERVATIONS_ADMIN = 'CLEAR_ALL_RESERVATIONS_ADMIN'

export const SET_ALL_PARAMS = 'SET_ALL_PARAMS'

export const REQUEST_GET_RESERVATION_BY_ID = 'REQUEST_GET_RESERVATION_BY_ID'
export const SUCCESS_GET_RESERVATION_BY_ID = 'SUCCESS_GET_RESERVATION_BY_ID'
export const FAILURE_GET_RESERVATION_BY_ID = 'FAILURE_GET_RESERVATION_BY_ID'

export const REQUEST_UPDATE_RESERVATION_BY_ID =
  'REQUEST_UPDATE_RESERVATION_BY_ID'
export const SUCCESS_UPDATE_RESERVATION_BY_ID =
  'SUCCESS_UPDATE_RESERVATION_BY_ID'
export const FAILURE_UPDATE_RESERVATION_BY_ID =
  'FAILURE_UPDATE_RESERVATION_BY_ID'

export const GET_REQUEST_ALL_RESERVATIONS_FROM_SERVER =
  'GET_REQUEST_ALL_RESERVATIONS_FROM_SERVER'
export const GET_SUCCESS_ALL_RESERVATIONS_FROM_SERVER =
  'GET_SUCCESS_ALL_RESERVATIONS_FROM_SERVER'
export const GET_FAILURE_ALL_RESERVATIONS_FROM_SERVER =
  'GET_FAILURE_ALL_RESERVATIONS_FROM_SERVER'

export const CREATE_REQUEST_NEW_RESERVATION = 'CREATE_REQUEST_NEW_RESERVATION'
export const ADD_NEW_CLIENT_REQUEST_NEW_RESERVATION =
  'ADD_NEW_CLIENT_REQUEST_NEW_RESERVATION'
export const ADD_NEW_CLIENT_SUCCESS_NEW_RESERVATION =
  'ADD_NEW_CLIENT_SUCCESS_NEW_RESERVATION'
export const ADD_NEW_CLIENT_FAILURE_NEW_RESERVATION =
  'ADD_NEW_CLIENT_FAILURE_NEW_RESERVATION'
export const SUCCESS_REQUEST_NEW_RESERVATION = 'SUCCESS_REQUEST_NEW_RESERVATION'
export const FAILURE_REQUEST_NEW_RESERVATION = 'FAILURE_REQUEST_NEW_RESERVATION'

export const SUCCESS_SEND_WHATSAPP_TO_COORDINATOR =
  'SUCCESS_SEND_WHATSAPP_TO_COORDINATOR'
export const REQUEST_SEND_WHATSAPP_TO_COORDINATOR =
  'REQUEST_SEND_WHATSAPP_TO_COORDINATOR'
export const CLEAR_GESTION_RESERVATIONS = 'CLEAR_GESTION_RESERVATIONS'
export const REQUEST_UPDATE_STATE_GESTION_RESERVATIONS =
  'REQUEST_UPDATE_STATE_GESTION_RESERVATIONS'
export const SUCCESS_UPDATE_STATE_GESTION_RESERVATIONS =
  'SUCCESS_UPDATE_STATE_GESTION_RESERVATIONS'
export const FAILURE_UPDATE_STATE_GESTION_RESERVATIONS =
  'FAILURE_UPDATE_STATE_GESTION_RESERVATIONS'
export const SAVE_RESERVATION_UPDATE = 'SAVE_RESERVATION_UPDATE'

export const REQUEST_ADD_RESERVATION_TO_GOOGLE_SHEET =
  'REQUEST_ADD_RESERVATION_TO_GOOGLE_SHEET'
export const SUCCESS_ADD_RESERVATION_TO_GOOGLE_SHEET =
  'SUCCESS_ADD_RESERVATION_TO_GOOGLE_SHEET'
export const FAILURE_ADD_RESERVATION_TO_GOOGLE_SHEET =
  'FAILURE_ADD_RESERVATION_TO_GOOGLE_SHEET'

export const REQUEST_UPDATE_RESERVATION_TO_GOOGLE_SHEET =
  'REQUEST_UPDATE_RESERVATION_TO_GOOGLE_SHEET'
export const SUCCESS_UPDATE_RESERVATION_TO_GOOGLE_SHEET =
  'SUCCESS_UPDATE_RESERVATION_TO_GOOGLE_SHEET'
export const FAILURE_UPDATE_RESERVATION_TO_GOOGLE_SHEET =
  'FAILURE_UPDATE_RESERVATION_TO_GOOGLE_SHEET'

export const REQUEST_SEND_EMAIL_RESERVATION = 'REQUEST_SEND_EMAIL_RESERVATION'
export const SUCCESS_SEND_EMAIL_RESERVATION = 'SUCCESS_SEND_EMAIL_RESERVATION'
export const FAILURE_SEND_EMAIL_RESERVATION = 'FAILURE_SEND_EMAIL_RESERVATION'
