export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const SET_UNAUTHENTICATE = 'SET_UNAUTHENTICATE'
export const SET_AUTHENTICATE = 'SET_AUTHENTICATE'

export const LOADING_REQUEST_IMAGE_USER = 'LOADING_REQUEST_IMAGE_USER'
export const LOADING_SUCCESS_IMAGE_USER = 'LOADING_SUCCESS_IMAGE_USER'
export const LOADING_FAILURE_IMAGE_USER = 'LOADING_FAILURE_IMAGE_USER'

export const LOADING_REQUEST_IMAGE_USER_ADMIN =
  'LOADING_REQUEST_IMAGE_USER_ADMIN'
export const LOADING_SUCCESS_IMAGE_USER_ADMIN =
  'LOADING_SUCCESS_IMAGE_USER_ADMIN'
export const LOADING_FAILURE_IMAGE_USER_ADMIN =
  'LOADING_FAILURE_IMAGE_USER_ADMIN'

export const LOADING_REQUEST_UPDATE_USER = 'LOADING_REQUEST_UPDATE_USER'
export const LOADING_SUCCESS_UPDATE_USER = 'LOADING_SUCCESS_UPDATE_USER'
export const LOADING_FAILURE_UPDATE_USER = 'LOADING_FAILURE_UPDATE_USER'

export const SET_ALL_USERS = 'SET_ALL_USERS'
export const SET_USER_TO_EDIT = 'SET_USER_TO_EDIT'

export const SET_OPTION_ADMIN = 'SET_OPTION_ADMIN'

export const SET_ADD_NEW_USER = 'SET_ADD_NEW_USER'
export const CLEAR_ADD_NEW_USER = 'CLEAR_ADD_NEW_USER'

export const USER_SIGNUP_GOOGLE_REQUEST = 'USER_SIGNUP_GOOGLE_REQUEST'
export const USER_SIGNUP_GOOGLE_SUCCESS = 'USER_SIGNUP_GOOGLE_SUCCESS'
export const USER_SIGNUP_GOOGLE_FAILURE = 'USER_SIGNUP_GOOGLE_FAILURE'

export const USER_SIGNUP_FACEBOOK_REQUEST = 'USER_SIGNUP_FACEBOOK_REQUEST'
export const USER_SIGNUP_FACEBOOK_SUCCESS = 'USER_SIGNUP_FACEBOOK_SUCCESS'
export const USER_SIGNUP_FACEBOOK_FAILURE = 'USER_SIGNUP_FACEBOOK_FAILURE'
