export const LOADING_REQUEST_IMAGE_MARIACHI = 'LOADING_REQUEST_IMAGE_MARIACHI'
export const LOADING_SUCCESS_IMAGE_MARIACHI = 'LOADING_SUCCESS_IMAGE_MARIACHI'
export const LOADING_FAILURE_IMAGE_MARIACHI = 'LOADING_FAILURE_IMAGE_MARIACHI'

export const SET_ALL_MARIACHIS = 'SET_ALL_MARIACHIS'
export const SET_MARIACHI_TO_EDIT = 'SET_MARIACHI_TO_EDIT'

export const LOADING_REQUEST_UPDATE_MARIACHI = 'LOADING_REQUEST_UPDATE_MARIACH'
export const LOADING_SUCCESS_COORDINATOR_UPDATE_MARIACHI =
  'LOADING_SUCCESS_COORDINATOR_UPDATE_MARIACHI'
export const LOADING_SUCCESS_UPDATE_MARIACHI = 'LOADING_SUCCESS_UPDATE_MARIACH'
export const LOADING_FAILURE_UPDATE_MARIACHI = 'LOADING_FAILURE_UPDATE_MARIACH'
export const CLEAR_DATA_UPDATE_MARIACHI = 'CLEAR_DATA_UPDATE_MARIACHI'

export const ADD_IMAGES_FROM_DRIVER = 'ADD_IMAGES_FROM_DRIVER'
export const ADD_VIDEOS_FROM_DRIVER = 'ADD_VIDEOS_FROM_DRIVER'
export const ADD_NEW_COORDINATOR_DATA_TO_NEW_MARIACHI =
  'ADD_NEW_COORDINATOR_DATA_TO_NEW_MARIACHI'
export const ADD_NEW_MARIACHI_DATA_TO_NEW_MARIACHI =
  'ADD_NEW_MARIACHI_DATA_TO_NEW_MARIACHI'
export const ADD_NEW_SERVICE_DATA_TO_NEW_MARIACHI =
  'ADD_NEW_SERVICE_DATA_TO_NEW_MARIACHI'
export const FORM_POSITION_ADD_MARIACHI = 'FORM_POSITION_ADD_MARIACHI'
export const CLEAR_NEW_MARIACHI_DATA_LOCALSTORAGE =
  'CLEAR_NEW_MARIACHI_DATA_LOCALSTORAGE'

export const REQUEST_ADD_NEW_MARIACHI = 'REQUEST_ADD_NEW_MARIACHI'
export const SUCCESS_ADD_NEW_COORDINATOR_TO_MARIACHI =
  'SUCCESS_ADD_NEW_COORDINATOR_TO_MARIACHI'
export const SUCCESS_ADD_NEW_MARIACHI = 'SUCCESS_ADD_NEW_MARIACHI'
export const FAILURE_ADD_NEW_MARIACHI = 'FAILURE_ADD_NEW_MARIACHI'
export const CLEAR_ADD_NEW_MARIACHI = 'CLEAR_ADD_NEW_MARIACHI'
